import os
import tkinter as tk
from tkinter import filedialog, messagebox
from PIL import Image
import exiftool
import google.generativeai as genai
import customtkinter as ctk

model = None
directory_path = ""
generation_config = {
    "temperature": 0.7,
    "top_p": 0.95,
    "top_k": 64,
    "max_output_tokens": 8192,
    "response_mime_type": "text/plain",
}

def split_text(text, max_length):
    parts = text.split(',')
    result = []
    current = ''
    for part in parts:
        if len(current) + len(part) + 1 <= max_length:  
            if current:
                current += ',' + part
            else:
                current = part
        else:
            result.append(current)
            current = part
    if current:
        result.append(current)
    return result

def process_images(api_key, progressbar):
    global model, directory_path
    if not directory_path:
        messagebox.showerror("Error", "Please select a directory first.")
        return
    if not api_key:
        messagebox.showerror("Error", "Please enter the API Key.")
        return

    
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(model_name="gemini-1.5-flash")

    try:
        
        files = [os.path.join(directory_path, f) for f in os.listdir(directory_path) if os.path.isfile(os.path.join(directory_path, f))]

        
        for image_path in files:
            try:
                
                img = Image.open(image_path)

               
                title_result = model.generate_content(["get a short description for the image", img])
                tags_result = model.generate_content(["get relevant tags delimited by comma, not hashtags, for the images", img])

                
                max_length = 64
                tags_split = split_text(tags_result.text, max_length)

               
                with exiftool.ExifTool() as et:
                    commands = ["-overwrite_original", f'-Title={title_result.text}']
                    for i, part in enumerate(tags_split):
                        commands.append(f'-Keywords={part}')

                    
                    commands.append(image_path)
                    et.execute(*commands)

            except Exception as e:
                print(f"Error processing file {image_path}: {str(e)}")
                continue

        print("Processing complete.")
    
    except Exception as e:
        print(f"Error processing directory: {str(e)}")

def select_directory(dir_label):
    global directory_path
    directory_path = filedialog.askdirectory()
    if directory_path:
        dir_label.configure(text=f"Selected directory: {directory_path}")

ctk.set_appearance_mode("dark") 
ctk.set_default_color_theme("dark-blue")  
ctk.deactivate_automatic_dpi_awareness()

root = ctk.CTk()
root.title("Get Keyword")
root.geometry("568x766") 


def customize_label(label, text, font_size=45, pady=10, anchor="center"):
    label.configure(text=text, font=("Segoe UI Bold", font_size), fg_color="transparent", text_color='#6ccc4f') 
    label.pack(pady=pady, anchor=anchor)

def customize_main_label(label, text, font_size=12, pady=1, anchor="center"):
    label.configure(text=text, font=("Segoe UI Bold", font_size), fg_color="transparent")  
    label.pack(pady=pady, anchor=anchor)

def customize_regular_label(label, text, font_size=12, pady=1, anchor="center"):
    label.configure(text=text, font=("Segoe UI", font_size), fg_color="transparent")    
    label.pack(pady=pady, anchor=anchor)

def customize_entry(entry, show_char="*", width=250, height=30, border_color="#30232d", border_width=1, corner_radius=2):
    entry.configure(show=show_char, width=width, height=height, border_width=border_width, corner_radius=corner_radius)
    entry.pack(pady=10, anchor="center")

def customize_button(button, text, command, fg_color="transparent", hover_color="#6ccc4f", corner_radius=8, font_size=12):
    button.configure(text=text, command=command, fg_color=fg_color, hover_color=hover_color, corner_radius=corner_radius, font=("Segoe UI Bold", font_size))
    button.pack(pady=10, anchor="center")


header_frame = ctk.CTkFrame(root, fg_color="#101010", height=700, width=100, corner_radius=1)
header_frame.pack(fill="both", pady=(0, 10), anchor="n")


logo_label = ctk.CTkLabel(header_frame, text="")
logo_label.pack(pady=110, anchor="center")
customize_label(logo_label, "GetKey{word}", pady=(90,10))

label_3 = ctk.CTkLabel(header_frame)
customize_main_label(label_3, "Made Keyword & Title generated by Gemini AI", font_size=12,pady=(0,30))

select_frame = ctk.CTkFrame(header_frame, fg_color="transparent")
select_frame.pack(pady=10, padx=10, anchor="center")

select_button = ctk.CTkButton(select_frame, border_color="#6ccc4f", border_width=1, corner_radius=8)
customize_button(select_button, "Select Directory", command=lambda: select_directory(dir_label))

label_2 = ctk.CTkLabel(header_frame, pady=(20) )
customize_main_label(label_2, "© 2024 Kadang_Kesel", font_size=9)

frame = ctk.CTkFrame(root, fg_color="transparent")
frame.pack(padx=100, pady=30, anchor="center")

customize_main_label(ctk.CTkLabel(frame), "Enter your Gemini API key:", font_size=14)

api_key_entry = ctk.CTkEntry(frame)
customize_entry(api_key_entry)

dir_label = ctk.CTkLabel(select_frame)
customize_main_label(dir_label, "No directory selected")

def start_processing():
    api_key = api_key_entry.get()
    process_images(api_key, None)

process_button = ctk.CTkButton(frame, border_color="#6ccc4f", border_width=1, corner_radius=8)
customize_button(process_button, "Start", command=start_processing)

def open_url(url):
    import webbrowser
    webbrowser.open(url, new=1)

social_frame = ctk.CTkFrame(frame, fg_color="transparent")
social_frame.pack(pady=(120,0), anchor="center")

instagram_logo_path = r'.\assets\instagram.png'
paypal_logo_path = r'.\assets\paypal.png'
github_logo_path = r'.\assets\github.png'

instagram_button = ctk.CTkButton(social_frame,border_color="white", fg_color="transparent", hover_color="#eeeeee", border_width=0.6, corner_radius=8, image=ctk.CTkImage(Image.open(instagram_logo_path)), text="", width=32, height=32, command=lambda: open_url("https://www.instagram.com/hadiyuli_"))
instagram_button.pack(side="left", padx=10)

paypal_button = ctk.CTkButton(social_frame,border_color="white", fg_color="transparent", hover_color="#eeeeee", border_width=1, corner_radius=8, image=ctk.CTkImage(Image.open(paypal_logo_path)), text="", width=32, height=32, command=lambda: open_url("paypal.me/KadangKesel"))
paypal_button.pack(side="left", padx=10)

github_button = ctk.CTkButton(social_frame,border_color="white", fg_color="transparent",hover_color="#eeeeee", border_width=1, corner_radius=8, image=ctk.CTkImage(Image.open(github_logo_path)), text="", width=32, height=32, command=lambda: open_url("https://github.com/kadangkesel"))
github_button.pack(side="left", padx=10)

root.mainloop()
